// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKytLpDRAyW8Echi1v_umdaTBDF8h7bbE',
    appId: '1:460795861287:web:26b61a5c75a9a82c4cb102',
    messagingSenderId: '460795861287',
    projectId: 'chats-a9fb1',
    authDomain: 'chats-a9fb1.firebaseapp.com',
    storageBucket: 'chats-a9fb1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMqupLacqnelN-JCbaSpqd2pdmCO1vmbU',
    appId: '1:460795861287:android:e8b2072ee79234c24cb102',
    messagingSenderId: '460795861287',
    projectId: 'chats-a9fb1',
    storageBucket: 'chats-a9fb1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARuebJuWJLNTyXO7BjXuhpUtmEqSxn7js',
    appId: '1:460795861287:ios:21648acd9eb2e4584cb102',
    messagingSenderId: '460795861287',
    projectId: 'chats-a9fb1',
    storageBucket: 'chats-a9fb1.firebasestorage.app',
    iosBundleId: 'com.example.chats',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARuebJuWJLNTyXO7BjXuhpUtmEqSxn7js',
    appId: '1:460795861287:ios:21648acd9eb2e4584cb102',
    messagingSenderId: '460795861287',
    projectId: 'chats-a9fb1',
    storageBucket: 'chats-a9fb1.firebasestorage.app',
    iosBundleId: 'com.example.chats',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKytLpDRAyW8Echi1v_umdaTBDF8h7bbE',
    appId: '1:460795861287:web:876128b147293b694cb102',
    messagingSenderId: '460795861287',
    projectId: 'chats-a9fb1',
    authDomain: 'chats-a9fb1.firebaseapp.com',
    storageBucket: 'chats-a9fb1.firebasestorage.app',
  );
}
